[2023-01-03T00:01:29.144+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.load_to_postgres manual__2023-01-02T23:53:19.341738+00:00 [queued]>
[2023-01-03T00:01:29.208+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.load_to_postgres manual__2023-01-02T23:53:19.341738+00:00 [queued]>
[2023-01-03T00:01:29.216+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T00:01:29.221+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-01-03T00:01:29.221+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-03T00:01:29.291+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-02 23:53:19.341738+00:00
[2023-01-03T00:01:29.306+0000] {standard_task_runner.py:55} INFO - Started process 1720 to run task
[2023-01-03T00:01:29.317+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uk_accidents_etl_pipeline', 'load_to_postgres', 'manual__2023-01-02T23:53:19.341738+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/milestone_3.py', '--cfg-path', '/tmp/tmpwrwms3_t']
[2023-01-03T00:01:29.323+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask load_to_postgres
[2023-01-03T00:01:29.661+0000] {task_command.py:389} INFO - Running <TaskInstance: uk_accidents_etl_pipeline.load_to_postgres manual__2023-01-02T23:53:19.341738+00:00 [running]> on host 82068c2abeb3
[2023-01-03T00:01:29.975+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T23:53:19.341738+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T23:53:19.341738+00:00
[2023-01-03T00:01:40.755+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-03T00:01:40.958+0000] {logging_mixin.py:137} INFO - Table already exists
[2023-01-03T00:01:40.971+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-03T00:01:40.989+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=uk_accidents_etl_pipeline, task_id=load_to_postgres, execution_date=20230102T235319, start_date=20230103T000129, end_date=20230103T000140
[2023-01-03T00:01:41.063+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-03T00:01:41.152+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
