[2023-01-02T18:38:27.980+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.load_to_postgres manual__2023-01-02T18:29:32.736333+00:00 [queued]>
[2023-01-02T18:38:28.035+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: uk_accidents_etl_pipeline.load_to_postgres manual__2023-01-02T18:29:32.736333+00:00 [queued]>
[2023-01-02T18:38:28.037+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T18:38:28.038+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 3
[2023-01-02T18:38:28.040+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T18:38:28.103+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2023-01-02 18:29:32.736333+00:00
[2023-01-02T18:38:28.115+0000] {standard_task_runner.py:55} INFO - Started process 1160 to run task
[2023-01-02T18:38:28.124+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'uk_accidents_etl_pipeline', 'load_to_postgres', 'manual__2023-01-02T18:29:32.736333+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/milestone_3.py', '--cfg-path', '/tmp/tmp3z7w6tsk']
[2023-01-02T18:38:28.129+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask load_to_postgres
[2023-01-02T18:38:28.375+0000] {task_command.py:389} INFO - Running <TaskInstance: uk_accidents_etl_pipeline.load_to_postgres manual__2023-01-02T18:29:32.736333+00:00 [running]> on host 5137c6c0b664
[2023-01-02T18:38:28.675+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=uk_accidents_etl_pipeline
AIRFLOW_CTX_TASK_ID=load_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T18:29:32.736333+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T18:29:32.736333+00:00
[2023-01-02T18:38:40.582+0000] {logging_mixin.py:137} INFO - connected succesfully
[2023-01-02T18:46:22.796+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-02T18:46:25.760+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1160. PIDs of all processes in the group: [1160]
[2023-01-02T18:46:25.975+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1160
[2023-01-02T18:46:27.475+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
